theme: jekyll-theme-midnight
title: Michael Lubinsky 

# markdown            : kramdown
# markdown: GFM
# plugins:
#   - jekyll-optional-front-matter
# https://docs.github.com/en/pages  
# https://kramdown.gettalong.org/documentation.html
# https://github.github.com/gfm/
